version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused

issues:
  max-issues-per-linter: 0
  max-same-issues: 3

output:
  formats:
    text:
      print-linter-name: true
      print-issued-lines: true

