name: ssh-key-signer

networks:
  local:
    driver: bridge

volumes:
  db_data:

services:
  postgresql:
    image: postgres:17.4-alpine
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init_db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=root_pw
      - POSTGRES_USER=root
      - POSTGRES_DB=root
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "postgres_db"]
    container_name: app_db
    networks:
      - local