server:
  port: ${PORT:8088}

app:
  ca_user_path: ${CA_USER_PATH}
  ca_host_path: ${CA_HOST_PATH}

spring:
  profiles:
    active: @spring.profiles.active@
  application:
    name: ssh-key-signer
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH_URL}/realms/${OAUTH_REALM}
      client:
        registration:
          app:
            provider: app
            client-id: ${OAUTH_CLIENT}
            client-secret: ${OAUTH_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            scope: openid,profile,email
        provider:
          app:
            issuer-uri: ${OAUTH_URL}/realms/${OAUTH_REALM}
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org: error
    io:
      binarycodes: error

vaadin:
  allowed-packages: io.binarycodes.homelab.sshkeysigner, com.vaadin
  exclude-urls: /rest/**
  launch-browser: false
