OAUTH_CLIENT: my-test-client
OAUTH_CLIENT_SECRET: fu3hZgzTNHjUIGzZETKuHwQzNT9ptbFG
OAUTH_URL: http://localhost:8090
OAUTH_REALM: my-test-realm

DB_HOST: localhost
DB_PORT: 5432
DB_NAME: app_db
DB_USERNAME: app_user
DB_PASSWORD: app_user_pw

CA_USER_PATH: "user_ca_key"
CA_HOST_PATH: "host_ca_key"
