vaadin:
  launch-browser: true

logging:
  level:
    org:
      atmosphere: warn

keycloak:
  client: my-test-client
  client_secret: pK9P9s0cqoSeW9p5Jv8zR97jtDmiOJDi
  url: http://localhost:8090
  realm: my-test-realm

db:
  host: localhost
  port: 5432
  db_name: app_db
  username: app_user
  password: app_user_pw