vaadin:
  launch-browser: true

logging:
  level:
    org:
      atmosphere: warn


keycloak:
  client: devtest
  url: https://keycloak.homedns.pro
  realm: homelab

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/app_db
    username: app_user
    password: app_user_pw
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.url}/realms/${keycloak.realm}
      client:
        registration:
          devtest:
            provider: ${keycloak.client}
            client-id: ${keycloak.client}
            client-secret: WgUL31TbNhwK7WFMuAYnFp25OBww5nsA
            authorization-grant-type: authorization_code
            scope: openid,profile,email
        provider:
          devtest:
            issuer-uri: ${keycloak.url}/realms/${keycloak.realm}