vaadin:
  launch-browser: true

logging:
  level:
    org:
      atmosphere: warn
      springframework: warn
    io:
      binarycodes: trace

keycloak:
  client: my-test-client
  client_secret: NGMFDNlSqjxVWgqwOyZQ4NS2fY18BG0x
  url: http://localhost:8090
  realm: my-test-realm

db:
  host: localhost
  port: 5432
  db_name: app_db
  username: app_user
  password: app_user_pw