name: go-ssh-signer

on:
  push:
    branches: [ '*' ]
    paths:
      - go-ssh-signer/**
      - .github/workflows/go-ssh-signer-workflow.yml
      - .github/workflows/go-build.yml

jobs:
  set-version:
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.get-sha.outputs.short_sha }}
    steps:
      - name: Get short SHA
        id: get-sha
        run: echo "short_sha=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

  run:
    needs: set-version
    uses: ./.github/workflows/go-build.yml
    with:
      service: go-ssh-signer
      artifact: ssh-keysign
      artifactVersion: ${{ needs.set-version.outputs.short_sha }}
